/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const init_scene: () => [number, number, number];
export const scene_names: () => any;
export const save_scene: () => any;
export const load_scene: () => any;
export const toggle_noise: () => any;
export const toggle_smooth: () => any;
export const delete_scene: () => any;
export const set_scene_name: (a: number, b: number) => [number, number, number];
export const load_first_scene: () => any;
export const toggle_selection_shape: () => [number, number, number];
export const set_material_color: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number];
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_4: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const closure86_externref_shim_multivalue_shim: (a: number, b: number, c: any) => [number, number];
export const closure128_externref_shim: (a: number, b: number, c: any) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__he8d21531f809d811: (a: number, b: number) => void;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__hafc2f4123c64a717: (a: number, b: number) => void;
export const closure149_externref_shim: (a: number, b: number, c: any) => void;
export const closure161_externref_shim: (a: number, b: number, c: any) => void;
export const closure181_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
